### ISSUE TITLE
Segfault in initializeDb () at text/qfontdatabase.cpp:785 from /usr/lib64/libQt5Gui.so.5

### ISSUE THREAD

**Issue by Hello71** [splintermind/Dwarf-Therapist#33]
This is not an acceptable method of exiting.

```
Could not open  "$PWD/log/run.log"  for writing! "No such file or directory"

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7405555 in initializeDb() () from /usr/lib64/libQt5Gui.so.5
(gdb) bt
#0  0x00007ffff7405555 in initializeDb() () from /usr/lib64/libQt5Gui.so.5
#1  0x00007ffff7407185 in QFontDatabase::findFont(int, QFontPrivate const*, QFontDef const&, bool) () from /usr/lib64/libQt5Gui.so.5
#2  0x00007ffff740849e in QFontDatabase::load(QFontPrivate const*, int) () from /usr/lib64/libQt5Gui.so.5
#3  0x00007ffff73e2167 in QFontPrivate::engineForScript(int) const () from /usr/lib64/libQt5Gui.so.5
#4  0x00007ffff73fd953 in QFontMetrics::lineSpacing() const () from /usr/lib64/libQt5Gui.so.5
#5  0x00007ffff7c36cc8 in QLabelPrivate::sizeForWidth(int) const () from /usr/lib64/libQt5Widgets.so.5
#6  0x00007ffff7c37097 in QLabel::minimumSizeHint() const () from /usr/lib64/libQt5Widgets.so.5
#7  0x00007ffff7c37143 in QLabel::sizeHint() const () from /usr/lib64/libQt5Widgets.so.5
#8  0x00007ffff7b4440c in QWidgetItemV2::updateCacheIfNecessary() const () from /usr/lib64/libQt5Widgets.so.5
#9  0x00007ffff7b4470d in QWidgetItemV2::maximumSize() const () from /usr/lib64/libQt5Widgets.so.5
#10 0x00007ffff7b3395d in QBoxLayoutPrivate::setupGeom() [clone .part.31] () from /usr/lib64/libQt5Widgets.so.5
#11 0x00007ffff7b345ae in QBoxLayout::maximumSize() const () from /usr/lib64/libQt5Widgets.so.5
#12 0x00007ffff7b3395d in QBoxLayoutPrivate::setupGeom() [clone .part.31] () from /usr/lib64/libQt5Widgets.so.5
#13 0x00007ffff7b34b48 in QBoxLayout::setGeometry(QRect const&) () from /usr/lib64/libQt5Widgets.so.5
#14 0x00007ffff7b4050e in QLayoutPrivate::doResize(QSize const&) () from /usr/lib64/libQt5Widgets.so.5
#15 0x00007ffff7b41c90 in QLayout::activate() () from /usr/lib64/libQt5Widgets.so.5
#16 0x00007ffff7b5cbf3 in QWidget::setVisible(bool) () from /usr/lib64/libQt5Widgets.so.5
#17 0x00007ffff7b46181 in QStackedLayout::setCurrentIndex(int) () from /usr/lib64/libQt5Widgets.so.5
#18 0x00007ffff7b4658a in QStackedLayout::insertWidget(int, QWidget*) () from /usr/lib64/libQt5Widgets.so.5
#19 0x00007ffff7c97cf7 in QTabWidget::insertTab(int, QWidget*, QIcon const&, QString const&) () from /usr/lib64/libQt5Widgets.so.5
#20 0x000000000048bb2b in Ui_OptionsMenu::setupUi(QDialog*) ()
#21 0x000000000047e9ba in OptionsMenu::OptionsMenu(QWidget*) ()
#22 0x00000000004e1e31 in DwarfTherapist::DwarfTherapist(int&, char**) ()
#23 0x00000000004b337a in main ()
```

**Comment by anders-larsson** [comment]
Great find. Cannot believe I missed in #30.
Guess I'll have to hunt down directories called 'log' since apparently I've started DT from all kind of different locations.

**Comment by Hello71** [comment]
Wait, no, this is a different bug.

**Comment by anders-larsson** [comment]
@splintermind  said in #30 "Any other linux paths that should be checked by default?". That's what I meant :)

**Comment by Hello71** [comment]
after recompiling qtgui and dt with symbols:

```
#0  0x00007ffff7405555 in initializeDb () at text/qfontdatabase.cpp:785
#1  0x00007ffff7407185 in QFontDatabase::findFont (script=script@entry=2, fp=fp@entry=0x7ac530, request=..., multi=multi@entry=true) at text/qfontdatabase.cpp:2460
#2  0x00007ffff740849e in QFontDatabase::load (d=d@entry=0x7ac530, script=script@entry=2) at text/qfontdatabase.cpp:2611
#3  0x00007ffff73e2167 in QFontPrivate::engineForScript (this=0x7ac530, script=script@entry=2) at text/qfont.cpp:218
#4  0x00007ffff73fd953 in QFontMetrics::lineSpacing (this=<optimized out>) at text/qfontmetrics.cpp:333
#5  0x00007ffff7c36cc8 in QLabelPrivate::sizeForWidth(int) const () from /usr/lib64/libQt5Widgets.so.5
#6  0x00007ffff7c37097 in QLabel::minimumSizeHint() const () from /usr/lib64/libQt5Widgets.so.5
#7  0x00007ffff7c37143 in QLabel::sizeHint() const () from /usr/lib64/libQt5Widgets.so.5
#8  0x00007ffff7b4440c in QWidgetItemV2::updateCacheIfNecessary() const () from /usr/lib64/libQt5Widgets.so.5
#9  0x00007ffff7b4470d in QWidgetItemV2::maximumSize() const () from /usr/lib64/libQt5Widgets.so.5
#10 0x00007ffff7b3395d in QBoxLayoutPrivate::setupGeom() [clone .part.31] () from /usr/lib64/libQt5Widgets.so.5
#11 0x00007ffff7b345ae in QBoxLayout::maximumSize() const () from /usr/lib64/libQt5Widgets.so.5
#12 0x00007ffff7b3395d in QBoxLayoutPrivate::setupGeom() [clone .part.31] () from /usr/lib64/libQt5Widgets.so.5
#13 0x00007ffff7b34b48 in QBoxLayout::setGeometry(QRect const&) () from /usr/lib64/libQt5Widgets.so.5
#14 0x00007ffff7b4050e in QLayoutPrivate::doResize(QSize const&) () from /usr/lib64/libQt5Widgets.so.5
#15 0x00007ffff7b41c90 in QLayout::activate() () from /usr/lib64/libQt5Widgets.so.5
#16 0x00007ffff7b5cbf3 in QWidget::setVisible(bool) () from /usr/lib64/libQt5Widgets.so.5
#17 0x00007ffff7b46181 in QStackedLayout::setCurrentIndex(int) () from /usr/lib64/libQt5Widgets.so.5
#18 0x00007ffff7b4658a in QStackedLayout::insertWidget(int, QWidget*) () from /usr/lib64/libQt5Widgets.so.5
#19 0x00007ffff7c97cf7 in QTabWidget::insertTab(int, QWidget*, QIcon const&, QString const&) () from /usr/lib64/libQt5Widgets.so.5
#20 0x000000000048bb2b in Ui_OptionsMenu::setupUi (this=0x7b2eb0, OptionsMenu=OptionsMenu@entry=0x7b2ac0) at bin/release/ui_optionsmenu.h:350
#21 0x000000000047e9ba in OptionsMenu::OptionsMenu (this=0x7b2ac0, parent=<optimized out>) at src/optionsmenu.cpp:45
#22 0x00000000004e1e31 in DwarfTherapist::DwarfTherapist (this=0x7fffffffd4b0, argc=<optimized out>, argv=<optimized out>) at src/dwarftherapist.cpp:83
#23 0x00000000004b337a in main (argc=1, argv=0x7fffffffd618) at src/main.cpp:40
```

**Comment by Hello71** [comment]
rebuilding qt seems to have done something
